import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { Toaster } from "sonner";

import { Footer } from "@/components/layout/footer";
import { Navbar } from "@/components/layout/navigation/nav-bar";
import SessionProvider from "@/components/providers";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geistSans = Geist({
  variable: "--font-sans",
  subsets: ["latin"],
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Funnel+Display:wght@800&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} bg-[#f7f7f7] font-sans antialiased`}
      >
        <div>
          <Toaster position="bottom-center" />
          <Navbar />
          <SessionProvider>
            <main>{children}</main>
          </SessionProvider>
          <Footer />
        </div>
      </body>
    </html>
  );
}
