import type { Metadata } from "next";
import "./globals.css";
import SessionProvider from "@/components/providers";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { Geist, Geist_Mono } from "next/font/google";
import { Navbar } from "@/components/layout/navigation/Navbar";
const geistSans = Geist({
  variable: "--font-sans",
  subsets: ["latin"],
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} font-sans antialiased bg-[#f7f7f7]`}>
        <Navbar />
        <SessionProvider>
          <main>{children}</main>
        </SessionProvider>
      </body>
    </html>
  );
}
